[[main]]
name    = 'Home'
pageRef = '/'
weight  = 10

[[main]]
name    = 'CC Awards Nominees 2026 (NEW)'
pageRef = '/nominations'
weight  = 20

[[main]]
name    = 'Previous Awards'
pageRef = '/awards/awards-2025'
weight  = 30

[[main]]
name    = 'The Guild'
pageRef = '/guild'
weight  = 40

[[main]]
name    = 'Join Us'
pageRef = '/join'
weight  = 50
