[[main]]
name    = 'Home'
pageRef = '/'
weight  = 10

[[main]]
name    = 'Awards'
pageRef = '/awards/awards-2025'
weight  = 20

[[main]]
name    = 'The Guild'
pageRef = '/guild'
weight  = 50

[[main]]
name    = 'Join Us'
pageRef = '/join'
weight  = 50
