[[main]]
name    = 'Home'
pageRef = '/'
weight  = 10

[[main]]
name    = 'CCA 2026 Nominees (NEW!)'
pageRef = '/nominations'
weight  = 20

[[main]]
name    = 'Awards'
pageRef = '/awards/awards-2025'
weight  = 30

[[main]]
name    = 'The Guild'
pageRef = '/guild'
weight  = 40

[[main]]
name    = 'Join Us'
pageRef = '/join'
weight  = 50
