baseURL       = 'https://filmcriticsguild.com/'
languageCode  = 'en-us'
title         = 'Film Critics Guild'
theme         = 'fcg'
summaryLength = 23

[pagination]
pagerSize = 6

[menus]
[[menus.main]]
name    = 'Home'
pageRef = '/'
weight  = 10

[[menus.main]]
name    = 'Awards'
pageRef = '/awards/awards-2024'
weight  = 20

[[menus.main]]
name    = 'Reviews'
pageRef = '/reviews'
weight  = 20

[[menus.main]]
name    = 'The Guild'
pageRef = '/guild'
weight  = 40

[[menus.main]]
name    = 'Join Us'
pageRef = '/join'
weight  = 50

[module]
[module.hugoVersion]
extended = false
min      = "0.116.0"

[taxonomies]
critic  = 'critics'
mreview = 'mreviews'

[server]
[[server.headers]]
for = '/**'
[server.headers.values]
Access-Control-Allow-Origin = 'http://localhost:5173'
Content-Security-Policy     = 'script-src localhost:1313'
Referrer-Policy             = 'strict-origin-when-cross-origin'
X-Content-Type-Options      = 'nosniff'
X-Frame-Options             = 'DENY'
X-XSS-Protection            = '1; mode=block'

[params]
[params.images]
reviews = '/images/reviews'
