baseURL = 'https://main.dliea0vsedn1p.amplifyapp.com/'
languageCode = 'en-us'
title = 'Film Critics Guild'
theme = 'fcg'
summaryLength = 23


[pagination]
  pagerSize = 6

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Awards'
pageRef = '/awards/awards-2024'
weight = 20

[[menus.main]]
name = 'Reviews'
pageRef = '/reviews'
weight = 20

[[menus.main]]
name = 'The Guild'
pageRef = '/guild'
weight = 40

[[menus.main]]
name = 'Join'
pageRef = '/join'
weight = 50

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
